name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Latest Rust
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
        
      - name: Run Test
        run: go test ./... -v

      - name: Build
        id: build
        shell: bash
        run: |
          platforms=("linux/amd64" "windows/amd64" "darwin/amd64" "linux/arm64" "windows/arm64" "darwin/arm64" "js/wasm")
          for platform in "${platforms[@]}"; do
            IFS="/" read -r -a split <<< "$platform"
            GOOS=${split[0]}
            GOARCH=${split[1]}
            output_name="./bin/antilang-${GOOS}-${GOARCH}"
            if [ "$GOOS" = "windows" ]; then
              output_name+=".exe"
            elif [ "$GOOS" = "js" ]; then
              output_name+=".wasm"
              go_file_path="./web/wasm_build.go"
            else
              go_file_path="main.go"
            fi
            go build -o "$output_name" "$go_file_path"
          done

      - name: Release Tags
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./bin/*